---
SERVER_ENV: development
API_CLIENT_USERNAME: username
API_CLIENT_PASSWORD: password
UNITY_CLIENT_ID: client
UNITY_CLIENT_SECRET: secret
BROKER_TOKEN: token
BROKER_SENDER: Instantly
BROKER_CALLBACK_URL: https://instantly.localtunnel.me/api/v1/payment/callback
BROKER_BASE_URL: https://api.smsgh.com/usp
POSTGRES_DBNAME: instantly_test
POSTGRES_URL: user='' dbname=instantly_test sslmode=disable
MIGRATIONS_DIR: db/migrations
...
